MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.09.20

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,37 +4,60 @@
 language: generic
 
 os: osx
-osx_image: beta-xcode6.1
+osx_image: xcode6.4
 
 env:
   matrix:
-    
-    - CONDA_PY=27
+    - CONFIG=osx_python2.7
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "KDTwWahLld9REtPhwxG3eC794zl3XLHEeC9kD4oBBJ+pV6FV9G08oYq1vi3VNQq5AkqXVi4/kNDV4GQowYm/PpfET9nh1nvy6wAQsok5T/KKNMF6lAO1vzPpTlzGKS0jD0WvysIfsw4DfQbg1qMGEJoYrF5KfhkxFFmnRZcYmN3CevhzXNoqxTCrwHWTEhUbqh2g4heR2xnFbPZsGBfz7Xjn1rf3f/bthP1pojEA7f9AcV7xZpn8RVPek2JGQAMbGcPE8LRe6zSMT5b5ZvmT7M7dIgcfrG2Ng3Iuz9xdpY9XIyGLue4re0HNEdm7TJAPcjRUCLIpH+e2kQRfVvLoe4kBOsNWJ9AAZljwosENwPTDtluTIPSa4c+hdbxQSbrVChwhItFpnIROP4yHYEagHWBQayRNzZhuUKhhs4CQql6p2uUGjXHy33WyXXYuGEiFeI963rtL2pmoAaPTiOvCMnFjTu1+mwpQ479am7T99vtdVt4xw+z5QNWZb0UQjnkxkcCW0JI73fRMEBY6/D1+ETazdbXjsNlsU9OC7/sp5zvNlT9i24tF80741IAUPUD77tcYRLsj9q11IYv5runUZAM/7f0WZZU2xme5Mk6dEqFtPen1P53QnrpPu5mkhEj2fEUDyAFFyAHuiD3Nvu7MFfJxLLEYxSHqUGVAZgFwoS4="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
-      MINICONDA_URL="http://repo.continuum.io/miniconda"
+      echo ""
+      echo "Installing a fresh version of Miniconda."
+      MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
-      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
+      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
